andreligan/IT342-SerbisYou

README.md

Feature myprofile perolino

---

README.md
backend/serbisyo/.gitattributes
backend/serbisyo/.gitignore
backend/serbisyo/.mvn/wrapper/maven-wrapper.properties
backend/serbisyo/mvnw
backend/serbisyo/mvnw.cmd
backend/serbisyo/pom.xml
backend/serbisyo/src/main/java/edu/cit/serbisyo/SerbisyoApplication.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/RunningController.java
backend/serbisyo/src/main/resources/application.properties
backend/serbisyo/src/test/java/edu/cit/serbisyo/SerbisyoApplicationTests.java

Added a running backend setup
Modified developer profiles at READMe.md

Update README.md and add backend folder

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/UserAuthController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/UserAuthEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/UserAuthRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/UserAuthService.java

controller package
entity package
repository package
service package

Added Packages

---

.vscode/settings.json
backend/serbisyo/pom.xml
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/BookingController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/CustomerController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ServiceCategoryController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ServiceController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/TransactionController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/UserAuthController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/BookingEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/CustomerEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceCategoryEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/TransactionEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/BookingRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/CustomerRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ServiceCategoryRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ServiceRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/TransactionRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/BookingService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/CustomerService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceCategoryService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/TransactionService.java

Customer classes
Booking classes
Transaction classes
Service classes
ServiceCategory classes
uncommented first dependency in pom.xml for resolving annotations

Bacarisas Assigned Entity Classes and CRUD

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ReviewController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ServiceProviderController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/VerificationController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ReviewEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceProviderEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/VerificationEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ReviewRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ServiceProviderRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/VerificationRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ReviewService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceProviderService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/VerificationService.java

Add Review/Service Provider/Verification service, entity, repositor, and controller.

Add Review/Service Provider/Verification service, entity, repositor, and controller

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/MessageController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/NotificationController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/MessageEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/NotificationEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/MessageRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/NotificationRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/MessageService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/NotificationService.java

Codes in the
-Service
-Controller
-Entity
-Repository

Remaining entity classes

---

backend/serbisyo/.gitignore
backend/serbisyo/pom.xml
backend/serbisyo/src/main/java/edu/cit/serbisyo/config/SecurityConfig.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/CustomerController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/MessageController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/RunningController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/BookingEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ReviewEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceProviderEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/TransactionEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/VerificationEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ReviewRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ServiceProviderRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/VerificationRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/NotificationService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ReviewService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceProviderService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/TransactionService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/UserAuthService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/VerificationService.java
backend/serbisyo/src/main/resources/application.properties

fixed inconsistencies on class files seen in "files changed"
integrated Google's OAuth2login feature
- added SecurityConfig class
Modified gitignore located inside root backend
purpose: to ignore application properties

Feature bacarisas bug fixes

---

frontend_web/frontend_web/src/components/Footer.jsx
frontend_web/frontend_web/src/components/LandingPage.jsx

Work done for this commit:
Landing Page v2
Footer v1

Refined Landing Page design and made the Footer design

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/UserAuthController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/CustomerEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceProviderEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/UserAuthEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/UserAuthService.java
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/CustomerHomePage.jsx
frontend_web/frontend_web/src/components/LoginPopup.jsx
frontend_web/frontend_web/src/components/SignupStepWizard.jsx
frontend_web/frontend_web/src/main.jsx
frontend_web/frontend_web/vite.config.js

can register both customer and service provider
can login just customer. (with token)

Frontend Login Register

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/BookingEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/CustomerEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ReviewEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceProviderEntity.java

Added Annotations
@JsonIgnore to entities.
This is to prevent referencing back when fetching records (backend problem)

JasonIgnoreAnnotations

---

frontend_web/frontend_web/package-lock.json
frontend_web/frontend_web/package.json
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/BookServicePage.jsx
frontend_web/frontend_web/src/components/BrowseServicesPage.jsx
frontend_web/frontend_web/src/components/CustomerHomePage.jsx

Progress in this commit:
1. Added the Browse Services and Book Service Routes in App.jsx.
2. Made the Browse Services Page.
3. Made the Book Service Page (not yet finished).

Add Browse Services and Book Service Feature

---

frontend_web/frontend_web/src/components/BookServicePage.jsx

Added Time Field in the Book Service Feature

Added Time Field in the Book Service Feature

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/AddressEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/CustomerEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ReviewEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/ServiceProviderEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ServiceRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/AddressService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceProviderService.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ServiceService.java
frontend_web/frontend_web/package-lock.json
frontend_web/frontend_web/package.json
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/SignupStepWizard.jsx
frontend_web/frontend_web/src/components/autocomplete.css
frontend_web/frontend_web/src/components/service_provider/AddServicePage.jsx
frontend_web/frontend_web/src/components/service_provider/ServiceDetails.jsx
frontend_web/frontend_web/src/components/service_provider/ServiceProviderHomePage.jsx
frontend_web/frontend_web/src/components/service_provider/profile/AddressContent.jsx
frontend_web/frontend_web/src/components/service_provider/profile/BusinessDetailsContent.jsx
frontend_web/frontend_web/src/components/service_provider/profile/MyServicesContent.jsx

Frontend:
PSGC integration API
- fetch pilippine place addresses. (up-to-date data on Philippine Geographic Divisions)
SignupStepWizard
- removed creation of address for fast & easy signup (not overwhelming the user registration form too much)
AddressContent.jsx
- address crud
MyServicesContent.jsx
- about the price modification from price to priceRange
autocomplete.css
- for autofilling the address input fields
Backend:
-------------- Adress ---------
added foreign keys for address entity (cutsomerId and providerid)
- efficiency
- affected classes:
Customer (entity)
ServiceProvider (entity)
Address (entity, service)
----------Service ----------
modified String priceRange to int price.
- affected classes:
Service (service, repository, entity)

main work: address related features

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/MessageController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/MessageRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/MessageService.java
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/chat/ChatHeader.jsx
frontend_web/frontend_web/src/components/chat/ChatIcon.jsx
frontend_web/frontend_web/src/components/chat/ChatList.jsx
frontend_web/frontend_web/src/components/chat/ChatWindow.jsx
frontend_web/frontend_web/src/components/chat/Conversation.jsx
frontend_web/frontend_web/src/components/chat/MessageBubble.jsx
frontend_web/frontend_web/src/components/chat/UserSearch.jsx
frontend_web/frontend_web/src/components/chat/mockData.js
frontend_web/frontend_web/src/services/ChatService.js

users can search people and chat with them
users can send chats/messages
opening conversation fetches the messages done within the conversation.
chat list proper fetching
basta working properly ang sending of messages.

Feature chat

---

frontend_mobile/SerbisYo-IT342-G3/.idea/deploymentTargetDropDown.xml
frontend_mobile/SerbisYo-IT342-G3/.idea/vcs.xml
frontend_mobile/SerbisYo-IT342-G3/app/src/main/AndroidManifest.xml
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/AddServiceActivity.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/EditServiceActivity.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/LoginActivity.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/RegisterActivity.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/api/ServiceApiClient.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/api/UserApiClient.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/data/Service.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/res/drawable/ic_image_placeholder.xml
frontend_mobile/SerbisYo-IT342-G3/app/src/main/res/layout/activity_add_service.xml
frontend_mobile/SerbisYo-IT342-G3/app/src/main/res/layout/activity_edit_service.xml

- Modified ServiceApiClient.kt to use dynamic IP configuration from the local network
- Added BASE_URL configuration to target the computer's IP address from ipconfig
- Added user feedback for connection status

Implemented wireless connection  allowing the mobile app to communicate with the backend server over local network

---

frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/LandingPage.jsx
frontend_web/frontend_web/src/components/LoginPopup.jsx
frontend_web/frontend_web/src/components/SignupStepWizard.jsx

- landing page MUI to Tailwind css
- added specific routes to sign up steps; completion: go to dashboard = go back to landing page then redirects to the landing page
- clicking be a provider redirects to signup page /details setting account type to Service Provider automatically and shows the Service provider form
- clicking browse services redirects to signup page /details setting account type to Customer automatically and shows the Customer form
- required input fields before navigating to the next sign up step -> SignupStepWizard.jsx
- default landing page for roles are customerHomepage or serviceProviderHomePage - RBAC

Build landing page

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/NotificationEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/NotificationService.java
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/chat/Conversation.jsx
frontend_web/frontend_web/src/components/notifications/NotificationDropdown.jsx
frontend_web/frontend_web/src/components/notifications/NotificationIcon.jsx
frontend_web/frontend_web/src/components/notifications/NotificationItem.jsx
frontend_web/frontend_web/src/components/notifications/NotificationsPage.jsx
frontend_web/frontend_web/src/services/ChatService.js
frontend_web/frontend_web/src/services/NotificationService.js

**notification feature**
achieved:
- message Notification creation
- message fetching
- filtered by the receiver of the notification
- only display latest message from the sender if many messages are SENT and unread
- clicking mark all as read will make mark the message status as READ then the notification for that message will be deleted.
to do:
- clicking on the notification should mark every message to READ and delete every notification from the sender.
- clicking the notification should open the chat or conversation with the sender.
- view all notifications (dedicated page?)

Feature message notification

---

frontend_web/frontend_web/src/services/NotificationService.js

clicking inidvidual message notification from list will update all sender's messages status to READ

Merge origin/main into feature-message-notification

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ReviewController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/ServiceController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/BookingRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/repository/ReviewRepository.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/ReviewService.java
frontend_web/frontend_web/src/App.jsx
frontend_web/frontend_web/src/components/BrowseServicesPage.jsx
frontend_web/frontend_web/src/components/customer/CustomerProfilePage.jsx
frontend_web/frontend_web/src/components/filters/FilterComponents.jsx
frontend_web/frontend_web/src/components/filters/ServiceFilters.jsx
frontend_web/frontend_web/src/components/modals/ServiceDetailsModal.jsx
frontend_web/frontend_web/src/components/service_provider/ServiceProviderProfile.jsx

Mainchanges:
browse services section

Build service provider profiles seen by customers

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/controller/UserAuthController.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/UserAuthService.java
frontend_web/frontend_web/src/components/BrowseServicesPage.jsx
frontend_web/frontend_web/src/components/customer/profile/CustomerProfileContent.jsx
frontend_web/frontend_web/src/components/modals/ServiceDetailsModal.jsx
frontend_web/frontend_web/src/components/service_provider/profile/ProfileContent.jsx
frontend_web/frontend_web/src/hooks/useAddressManager.js

customer side address adding and updating issue: removed updating customer profile after adding or updating address.
api call causes 404 error in console.
efficient fetching of profile details 
User Auth - getting users by id para mapadali nalang sad. pero wa ra nako giremove ang existing methods para di muerror s mobile
service provider profile fetching and displaying issue: fixed through (in browse services page, creation of service provider objects includes their respective profile pictures)

Bugfix profile fetch service provider profile picture

---

backend/serbisyo/src/main/java/edu/cit/serbisyo/entity/NotificationEntity.java
backend/serbisyo/src/main/java/edu/cit/serbisyo/service/BookingService.java
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/adapters/NotificationAdapter.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/api/MessageApiClient.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/data/Notification.kt
frontend_mobile/SerbisYo-IT342-G3/app/src/main/java/com/example/serbisyo_it342_g3/fragments/NotificationsFragment.kt

Fixed the notification feature

notification_feature_in_mobile

---

frontend_web/frontend_web/src/components/service_provider/AddServicePage.jsx

add service page fixed api calls

---

frontend_web/frontend_web/src/components/service_provider/profile/BusinessDetailsContent.jsx
frontend_web/frontend_web/src/components/service_provider/profile/MyServicesContent.jsx
frontend_web/frontend_web/src/components/service_provider/profile/ProfileContent.jsx
frontend_web/frontend_web/src/components/service_provider/profile/ScheduleContent.jsx
frontend_web/frontend_web/src/utils/apiConfig.js

fixed api calls in service provider profile

---

frontend_web/frontend_web/src/components/service_provider/profile/ScheduleContent.jsx
frontend_web/frontend_web/src/components/shared/AddressForm.jsx
frontend_web/frontend_web/src/utils/addressApi.js

address and schedule content api calls fixed service provider

address and schedule content api calls fixed service provider
